// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf-VrdFB5-fM-KK7HQAJ0I2bjF-fCI1M0',
    appId: '1:276205139693:web:821192b0376fc346d6fee4',
    messagingSenderId: '276205139693',
    projectId: 'rababa-3b366',
    authDomain: 'rababa-3b366.firebaseapp.com',
    storageBucket: 'rababa-3b366.appspot.com',
    measurementId: 'G-K0TRSY5D3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtsPgRlLWcMNX0nn4RsjvqDdDHbe8cLKM',
    appId: '1:276205139693:android:60f927a637c0e2e9d6fee4',
    messagingSenderId: '276205139693',
    projectId: 'rababa-3b366',
    storageBucket: 'rababa-3b366.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxW1qx1XRPKKzIO6w7R_R-eNMhMw7-x-4',
    appId: '1:276205139693:ios:39cd373ee50961d0d6fee4',
    messagingSenderId: '276205139693',
    projectId: 'rababa-3b366',
    storageBucket: 'rababa-3b366.appspot.com',
    iosClientId: '276205139693-armivjj8g4nea9is819t6qhqq452ieec.apps.googleusercontent.com',
    iosBundleId: 'com.Rababa.rababa',
  );
}
